# Site Build Settings

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Site identity (also used by jekyll-seo-tag and the atom feed)
title:               "Ella Iles"
description:         "Personal Website"
author:              "Ella Iles"
url:                 "https://ellailes.github.io"
baseurl:             ""

# Don't copy these into the built site
exclude:
  - Gemfile
  - Gemfile.lock
  - millennial.gemspec
  - README.md
  - LICENSE.md
  - vendor

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
